services:
  postgres:
    image: "postgres:16-alpine"
    ports:
      - "127.0.0.1:9678:5432"
    shm_size: 2gb
    restart: always
    environment:
      - POSTGRES_PASSWORD=change_me_plz
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=nextbooru
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:9679:8080"
volumes:
  pgdata:
